"use client"

import { getLocale } from "@/lib/i18n"
import { useState } from "react"

const labels = {
  fa: { title: "درخواست خرید حرفه‌ای", text: "برای پزشکان، ادیولوژیست‌ها و مراکز درمانی. این فرم تا زمان اتصال سرویس بررسی درخواست‌ها، اطلاعات را ذخیره یا ارسال نمی‌کند.", first: "نام", last: "نام خانوادگی", phone: "تلفن", email: "ایمیل", type: "نوع فعالیت", organization: "نام سازمان یا کلینیک", license: "شناسه حرفه‌ای یا مجوز", city: "شهر", notes: "توضیحات (اختیاری)", submit: "ارسال درخواست", notice: "ارسال آنلاین هنوز فعال نیست؛ لطفاً پس از راه‌اندازی کانال پشتیبانی، درخواست خود را ثبت کنید." },
  en: { title: "Professional purchasing application", text: "For doctors, audiologists, and care organizations. Until an application-review service is connected, this form does not store or submit data.", first: "First name", last: "Last name", phone: "Phone", email: "Email", type: "Professional type", organization: "Organization or clinic", license: "Professional or license ID", city: "City", notes: "Notes (optional)", submit: "Submit application", notice: "Online submission is not active yet. Please register your application once the support channel is available." },
}

export default function ProfessionalApplicationForm() {
  const locale = getLocale(typeof document === "undefined" ? undefined : document.documentElement.lang)
  const t = labels[locale]
  const [notice, setNotice] = useState(false)
  const field = "w-full rounded-lg border border-ui-border-base bg-ui-bg-base px-3 py-3 text-sm outline-none focus:border-teal-700 focus:ring-2 focus:ring-teal-700/20"
  return <section className="rounded-2xl border border-ui-border-base bg-ui-bg-subtle p-6 small:p-10"><h2 className="text-2xl font-semibold">{t.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-ui-fg-subtle">{t.text}</p><form className="mt-8 grid gap-4 small:grid-cols-2" onSubmit={(event) => { event.preventDefault(); setNotice(true) }}><label className="text-sm font-medium">{t.first}<input required name="first_name" autoComplete="given-name" className={`${field} mt-2`} /></label><label className="text-sm font-medium">{t.last}<input required name="last_name" autoComplete="family-name" className={`${field} mt-2`} /></label><label className="text-sm font-medium">{t.phone}<input required name="phone" type="tel" autoComplete="tel" className={`${field} mt-2`} /></label><label className="text-sm font-medium">{t.email}<input required name="email" type="email" autoComplete="email" className={`${field} mt-2`} /></label><label className="text-sm font-medium">{t.type}<select required name="professional_type" className={`${field} mt-2`}><option value="">—</option><option value="doctor">{locale === "fa" ? "پزشک" : "Doctor"}</option><option value="audiologist">{locale === "fa" ? "ادیولوژیست" : "Audiologist"}</option><option value="clinic">{locale === "fa" ? "کلینیک / سازمان درمانی" : "Clinic / medical organization"}</option></select></label><label className="text-sm font-medium">{t.organization}<input required name="organization" autoComplete="organization" className={`${field} mt-2`} /></label><label className="text-sm font-medium">{t.license}<input name="professional_identifier" className={`${field} mt-2`} /></label><label className="text-sm font-medium">{t.city}<input required name="city" autoComplete="address-level2" className={`${field} mt-2`} /></label><label className="text-sm font-medium small:col-span-2">{t.notes}<textarea name="notes" rows={4} className={`${field} mt-2 resize-y`} /></label><div className="small:col-span-2"><button type="submit" className="rounded-lg bg-teal-700 px-5 py-3 text-sm font-medium text-white hover:bg-teal-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700">{t.submit}</button>{notice && <p role="status" className="mt-3 text-sm text-ui-fg-subtle">{t.notice}</p>}</div></form></section>
}
