import { sdk } from "../../lib/client"
import { Badge, Button, Input, Select, Table } from "@medusajs/ui"
import { useEffect, useState } from "react"

type Application = { id: string; first_name: string; last_name: string; professional_type: string; organization_name?: string; email: string; city: string; status: string; created_at: string }
export default function ProfessionalApplicationsTable() {
  const [items, setItems] = useState<Application[]>([]); const [status, setStatus] = useState("pending"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); setError(""); try { const result = await sdk.client.fetch<{ professional_applications: Application[] }>(`/admin/professional-applications?limit=50${status ? `&status=${status}` : ""}`, { method: "GET" }); setItems(result.professional_applications) } catch { setError("Could not load professional applications.") } finally { setLoading(false) } }
  useEffect(() => { load() }, [status])
  return <div className="p-6"><div className="mb-4 flex gap-2"><Select value={status} onValueChange={setStatus}><Select.Trigger><Select.Value placeholder="Status" /></Select.Trigger><Select.Content>{["pending", "approved", "rejected", "needs_information"].map(value => <Select.Item key={value} value={value}>{value}</Select.Item>)}</Select.Content></Select><Button variant="secondary" onClick={load}>Refresh</Button></div>{error && <p className="mb-4 text-ui-fg-error">{error}</p>}<Table><Table.Header><Table.Row><Table.HeaderCell>Applicant</Table.HeaderCell><Table.HeaderCell>Type</Table.HeaderCell><Table.HeaderCell>Organization</Table.HeaderCell><Table.HeaderCell>Email</Table.HeaderCell><Table.HeaderCell>City</Table.HeaderCell><Table.HeaderCell>Status</Table.HeaderCell><Table.HeaderCell>Submitted</Table.HeaderCell></Table.Row></Table.Header><Table.Body>{loading ? <Table.Row><Table.Cell colSpan={7}>Loading…</Table.Cell></Table.Row> : items.length ? items.map(app => <Table.Row key={app.id}><Table.Cell>{app.first_name} {app.last_name}</Table.Cell><Table.Cell>{app.professional_type}</Table.Cell><Table.Cell>{app.organization_name || "—"}</Table.Cell><Table.Cell>{app.email}</Table.Cell><Table.Cell>{app.city}</Table.Cell><Table.Cell><Badge>{app.status}</Badge></Table.Cell><Table.Cell>{new Date(app.created_at).toLocaleDateString()}</Table.Cell></Table.Row>) : <Table.Row><Table.Cell colSpan={7}>No applications found.</Table.Cell></Table.Row>}</Table.Body></Table></div>
}
