import type { Locale } from "@/lib/i18n"

export type InformationalPageKey = "about" | "contact" | "faq"

const content = {
  fa: {
    about: {
      eyebrow: "درباره EarMed",
      title: "همراه خرید لوازم مراقبت از شنوایی",
      intro: "EarMed فروشگاهی برای تهیه لوازم جانبی، محصولات مراقبتی و اقلام مصرفی مرتبط با شنوایی است. تمرکز ما ارائه مسیر خریدی روشن برای مشتریان و خریداران حرفه‌ای است.",
      scopeTitle: "چه محصولاتی ارائه می‌کنیم؟",
      scopeBody: "مجموعه فروشگاه شامل باتری سمعک، محصولات تمیزکاری و کنترل رطوبت، فیلترها، تیوب‌ها و دیگر قطعات و لوازم مصرفی مرتبط است. خودِ سمعک در این فروشگاه عرضه نمی‌شود.",
      categoriesTitle: "دامنه محصولات",
      categories: ["باتری‌های سمعک", "تمیزکاری و مراقبت", "خشک‌کردن و کنترل رطوبت", "قطعات و لوازم مصرفی"],
      professionalTitle: "خرید حرفه‌ای",
      professionalBody: "پزشکان، شنوایی‌شناسان، کلینیک‌ها و سازمان‌های درمانی می‌توانند پس از ایجاد حساب، درخواست حرفه‌ای خود را ثبت کنند. دسترسی حرفه‌ای فقط پس از بررسی و تأیید فعال می‌شود.",
      professionalAction: "آشنایی با خرید حرفه‌ای",
      approachTitle: "رویکرد ما",
      approachItems: ["نمایش شفاف مشخصات و وضعیت موجودی ثبت‌شده", "تفکیک روشن خرید عادی و مسیر خرید حرفه‌ای", "امکان پیگیری سفارش و وضعیت پرداخت از حساب کاربری"],
      metadataTitle: "درباره ما",
      metadataDescription: "درباره دامنه محصولات و مسیر خرید مشتریان و متخصصان در EarMed Store.",
    },
    contact: {
      eyebrow: "ارتباط با EarMed",
      title: "تماس با ما",
      intro: "راه‌های ارتباطی رسمی فروشگاه پس از نهایی‌شدن اطلاعات کسب‌وکار در همین صفحه منتشر می‌شوند.",
      detailsTitle: "اطلاعات تماس",
      unavailable: "اطلاعات تماس هنوز پیکربندی نشده است. تا زمان انتشار اطلاعات رسمی، از ثبت اطلاعات شخصی در کانال‌های غیررسمی خودداری کنید.",
      phone: "تلفن",
      email: "ایمیل",
      address: "نشانی",
      hours: "ساعات پاسخ‌گویی",
      noteTitle: "پیش از تماس",
      note: "برای پیگیری سفارش، وضعیت سفارش و پرداخت دستی را ابتدا در حساب کاربری بررسی کنید. اطلاعات تماس نهایی و شیوه پاسخ‌گویی پس از پیکربندی رسمی نمایش داده خواهد شد.",
      metadataTitle: "تماس با ما",
      metadataDescription: "راه‌های ارتباط رسمی با EarMed Store و راهنمای پیگیری سفارش.",
    },
    faq: {
      eyebrow: "راهنمای خرید",
      title: "سوالات متداول",
      intro: "پاسخ کوتاه به پرسش‌های رایج درباره محصولات، سفارش، پرداخت دستی و خرید حرفه‌ای.",
      items: [
        ["EarMed چه محصولاتی ارائه می‌کند؟", "لوازم جانبی، محصولات مراقبتی و اقلام مصرفی مرتبط با شنوایی، از جمله باتری، محصولات تمیزکاری و رطوبت‌گیر و قطعات مصرفی در فروشگاه ارائه می‌شوند."],
        ["آیا خودِ سمعک در فروشگاه فروخته می‌شود؟", "خیر. دامنه فعلی فروشگاه لوازم جانبی، محصولات مراقبت و اقلام مصرفی مرتبط است و شامل فروش سمعک نمی‌شود."],
        ["ثبت سفارش چگونه انجام می‌شود؟", "محصول را به سبد خرید اضافه کنید، نشانی و روش ارسال موجود را در تسویه‌حساب انتخاب کنید و پس از بازبینی، سفارش را ثبت کنید."],
        ["آیا برای خرید به حساب کاربری نیاز دارم؟", "برای تکمیل مسیرهایی که به سفارش، پرداخت و پیگیری وضعیت متصل هستند، ورود به حساب کاربری لازم است."],
        ["پرداخت دستی چگونه بررسی می‌شود؟", "پس از ثبت سفارش، دستورالعمل پرداخت پیکربندی‌شده نمایش داده می‌شود. ثبت سفارش به معنی تأیید پرداخت نیست و وضعیت فقط پس از بررسی رسید تغییر می‌کند."],
        ["رسید پرداخت را چگونه ارسال کنم؟", "در صفحه تأیید یا جزئیات سفارش می‌توانید فایل معتبر تصویر یا PDF را ارسال کنید. رسید ارسال‌شده تا زمان بررسی در وضعیت در انتظار باقی می‌ماند."],
        ["وضعیت سفارش و پرداخت را کجا ببینم؟", "سفارش‌ها و وضعیت پرداخت دستی از بخش سفارش‌های حساب کاربری قابل مشاهده هستند."],
        ["حساب حرفه‌ای چیست؟", "پزشکان، شنوایی‌شناسان، کلینیک‌ها و سازمان‌های درمانی می‌توانند درخواست حرفه‌ای ثبت کنند. دسترسی حرفه‌ای پس از بررسی و تأیید مدیر فعال می‌شود."],
        ["چه کسی می‌تواند درخواست پیش‌فاکتور ثبت کند؟", "درخواست پیش‌فاکتور برای مشتری حرفه‌ای تأییدشده و مطابق سطح دسترسی واقعی حساب در دسترس است."],
        ["روش و هزینه ارسال چگونه مشخص می‌شود؟", "گزینه‌های ارسال پیکربندی‌شده برای منطقه و سبد خرید در مرحله ارسال نمایش داده می‌شوند. اگر گزینه‌ای در دسترس نباشد، تکمیل سفارش ممکن نیست."],
      ],
      metadataTitle: "سوالات متداول",
      metadataDescription: "پاسخ به سوالات رایج درباره خرید، پرداخت دستی، سفارش و حساب حرفه‌ای EarMed Store.",
    },
  },
  en: {
    about: {
      eyebrow: "About EarMed",
      title: "A clearer way to buy hearing-care supplies",
      intro: "EarMed is a storefront for hearing-related accessories, care products, and consumables. It provides a clear purchasing path for customers and professional buyers.",
      scopeTitle: "What the store provides",
      scopeBody: "The catalog covers hearing-aid batteries, cleaning and moisture-control products, filters, tubing, and other related parts and consumables. Hearing aids themselves are not sold through this storefront.",
      categoriesTitle: "Product scope",
      categories: ["Hearing-aid batteries", "Cleaning and care", "Drying and moisture control", "Parts and consumables"],
      professionalTitle: "Professional purchasing",
      professionalBody: "Doctors, audiologists, clinics, and medical organizations can create an account and submit a professional application. Professional access is enabled only after review and approval.",
      professionalAction: "Explore professional purchasing",
      approachTitle: "Our approach",
      approachItems: ["Clear display of recorded product details and availability", "A distinct path for retail and professional purchasing", "Order and manual-payment status available from the customer account"],
      metadataTitle: "About Us",
      metadataDescription: "Learn about EarMed Store's product scope and purchasing paths for customers and professionals.",
    },
    contact: {
      eyebrow: "Contact EarMed",
      title: "Contact Us",
      intro: "Official store contact channels will be published here when the business information is finalized.",
      detailsTitle: "Contact information",
      unavailable: "Contact details have not been configured yet. Until official details are published, avoid sharing personal information through unofficial channels.",
      phone: "Phone",
      email: "Email",
      address: "Address",
      hours: "Working hours",
      noteTitle: "Before contacting us",
      note: "For an existing order, first review its order and manual-payment status in your account. Final contact details and response channels will appear here after official configuration.",
      metadataTitle: "Contact Us",
      metadataDescription: "Official EarMed Store contact information and order-tracking guidance.",
    },
    faq: {
      eyebrow: "Shopping help",
      title: "Frequently Asked Questions",
      intro: "Short answers about products, ordering, manual payment, and professional purchasing.",
      items: [
        ["What products does EarMed provide?", "The store provides hearing-related accessories, care products, and consumables such as batteries, cleaning and moisture-control products, and replacement parts."],
        ["Are hearing aids sold through the store?", "No. The current catalog is for related accessories, care products, and consumables; it does not include hearing aids themselves."],
        ["How do I place an order?", "Add products to the cart, choose an available address and shipping method at checkout, review the details, and place the order."],
        ["Do I need an account?", "Signing in is required for flows connected to order creation, manual payment, and status tracking."],
        ["How is manual payment reviewed?", "After order creation, the configured payment instructions are shown. Creating the order does not approve payment; its status changes only after receipt review."],
        ["How do I upload a receipt?", "A valid image or PDF can be submitted from the confirmation or order details experience. The receipt remains pending until it is reviewed."],
        ["Where can I track my order and payment?", "Orders and authoritative manual-payment statuses are available in the Orders section of your account."],
        ["What is a professional account?", "Doctors, audiologists, clinics, and medical organizations can apply. Professional access is enabled only after admin review and approval."],
        ["Who can request a quote?", "Quote requests are available to approved professional customers according to the account's actual authorization."],
        ["How are shipping methods and costs determined?", "Shipping options configured for the region and cart are shown during checkout. Checkout cannot be completed if no applicable option is available."],
      ],
      metadataTitle: "FAQ",
      metadataDescription: "Answers about EarMed Store ordering, manual payment, order status, and professional accounts.",
    },
  },
} as const

export const getInformationalContent = (locale: Locale) => content[locale]
